version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fy7171cd
      POSTGRES_DB: family_tree_db
    ports:
      - "5432:5432"

  flask:
    build: ./backend
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      DATABASE_URL: postgresql://postgres:fy7171cd@db:5432/family_tree_db
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always  # автоматичний перезапуск у випадку невдачі

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - flask
